### ISSUE TITLE
JRE fatal error when nBlocks=1

### ISSUE THREAD

**Issue by YikangHua** [crillab/jkahypar#9]
```
int nbVertices = 7;
int nbHyperedges = 4;
Hypergraph graph = HypergraphBuilder.createHypergraph(nbVertices, nbHyperedges)
                .withHyperedge(UnweightedHyperedge.joining(1, 2).withWeight(2))
                .withHyperedge(UnweightedHyperedge.joining(1, 7, 5, 6).withWeight(3))
                .withHyperedge(UnweightedHyperedge.joining(5, 6, 4).withWeight(8))
                .withHyperedge(UnweightedHyperedge.joining(2, 3, 4).withWeight(7))
                .withVertexWeight(1, 5)
                .withVertexWeight(2, 1)
                .withVertexWeight(3, 8)
                .withVertexWeight(4, 7)
                .withVertexWeight(5, 3)
                .withVertexWeight(6, 9)
                .withVertexWeight(7, 3)
                .build();
try (var context = new KahyparContext()) {
      context.configureFrom("src/main/resources/km1_kKaHyPar_sea20.ini");
      context.setImbalance(0.03);
      context.setNumberOfBlocks(1);
      KahyparPartitioner partitioner = context.createPartitionerFor(graph);
      HypergraphPartition partition = partitioner.computePartition();
      int objective = partition.objectiveValue();
      System.out.println(objective);
}
```
almost the same as the demo in Readme, but set the number of blocks equals to 1. This will lead to a JRE fatal error.

**Comment by romainwallon** [comment]
Hello,

Could you add information about your system, the version of Java you are using, as well as the exact error message you get?

**Comment by YikangHua** [comment]
MacOS 14.2.1 (23C71) with M3, Java 17.0.10

**Comment by YikangHua** [comment]
Error Message: 
A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x000000012d6317e4, pid=82427, tid=9987

JRE version: Java(TM) SE Runtime Environment (17.0.10+11) (build 17.0.10+11-LTS-240)
Java VM: Java HotSpot(TM) 64-Bit Server VM (17.0.10+11-LTS-240, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
Problematic frame:
C  [jna7069118735629409437.tmp+0x317e4]  kahypar::ds::ConnectivitySets<int, unsigned int>::ConnectivitySet::add(int)+0x2c

No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again.

**Comment by romainwallon** [comment]
I think the segmentation fault is produced by KaHyPar itself, so the issue is not in the Java wrapper.

My guess is that KaHyPar expects to have at least two blocks for the partition to compute. Indeed, if you ask for only one block, there is no "real" partition to compute : you would in this case get a block with all the vertices inside.
